# -*- coding: utf-8 -*-
"""A05_BD_Campeonato.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_GtzB6R_8A5Jo1CB58ECPJzT6SZcGNLC

# Importação e instalação de pacotes
"""

!pip install mysql
!pip install mysql-connector

import pandas as pd
import mysql.connector

"""# Conexão com o banco de dados (Google Cloud)"""

#db= mysql.connector.connect(host="35.198.30.132",user="cdd003", passwd="12345678",db="campeonato")
db= mysql.connector.connect(host="35.239.50.225",user="root", passwd="12345678",db="campeonato")
cursor = db.cursor()

print("Conectado com sucesso!")

"""# Exibição dos metadados do BD"""

#Exibir as tabelas do banco de dados
print("BD CAMPEONATO") 
cursor.execute("show tables;");
for i in cursor:
    print(i)

print("\nTabela EQUIPE") 
cursor.execute("describe EQUIPE;");
for i in cursor:
    print(i)

print("\nTabela PARTIDA") 
cursor.execute("describe PARTIDA;");
for i in cursor:
    print(i)

print("\nTabela JOGADOR") 
cursor.execute("describe JOGADOR;");
for i in cursor:
    print(i)

print("\nTabela POSICAO") 
cursor.execute("describe POSICAO;");
for i in cursor:
    print(i)

print("\nTabela JOGA") 
cursor.execute("describe JOGA;");
for i in cursor:
    print(i)

"""# Consultas SQL simples"""

#Exibir os dados de todas as equipes
print("EQUIPES:") 
cursor.execute(
    """SELECT * 
       FROM EQUIPE;""");
for i in cursor:
    print(i)

#Exibir os dados dos jogadores da equipe 'America F. C.'
print("\nJOGADORES do America F. C.:") 
cursor.execute(
    """SELECT J.CPF, J.Nome, J.DataNascimento, J.Salario
       FROM   EQUIPE AS E, JOGADOR AS J
       WHERE   J.ECodigo = E.Codigo AND E.Nome = "America F. C.";""");
for i in cursor:
    print(i)

"""# Consultas SQL simples com Pandas"""

#Exibir os dados de todas as equipes com Pandas
print("EQUIPES:") 
SQL_Query = pd.read_sql_query(
    """SELECT * 
       FROM EQUIPE;""", db)
df = pd.DataFrame(SQL_Query, columns=['Codigo','Nome'])
print(df)

#Exibir os dados dos jogadores da equipe 'America F. C.'
print("\nJOGADORES do America F. C.:") 
SQL_Query = pd.read_sql_query(
    """SELECT J.CPF, J.Nome, J.DataNascimento, J.Salario
       FROM   EQUIPE AS E, JOGADOR AS J
       WHERE   J.ECodigo = E.Codigo AND E.Nome = "America F. C.";""", db);
df = pd.DataFrame(SQL_Query)
print(df)

"""# Operações com Pandas DataFrame"""

#Imprime o nome do jogador da posição 0 (via nome da coluna)
print(df.loc[0,'Nome'])

#Imprime o nome do jogador da posição 0 (via índice da coluna)
print(df.iloc[0,1])

#Alterando o salário do jogador da posição 0 para 100.000
df.loc[0,'Salario'] = 100000.00

#Converte DataFrame para list (matriz)
matriz = df.values.tolist()
print(matriz)

#Converte list (matriz) para DataFrame
df = pd.DataFrame(matriz,columns=['CPF', 'Nome', 'DataNascimento', 'Salario'])
print(df)

#Cria arquivo .csv a partir de um DataFrame
df.to_csv(r'Jogadores_America.csv', index = False)

"""# Consultas SQL dos exercícios

1. Adicionar a equipe 'Porto F. C.', de código 1053 à tabela EQUIPE com 0 vitórias, 0 derrotas e 0 empates.
"""

cursor.execute(
    """DELETE FROM EQUIPE
       WHERE Codigo=1053;""");

cursor.execute(
    """INSERT INTO EQUIPE VALUES
       ("Porto F. C.", 1053, 0, 0, 0);""");

"""2. Adicionar a posição 'Lateral direito' ao jogador de CPF '1098068753'."""

# A fazer

"""3. Exibir o código, o nome e o número de vitórias dos times com mais que 5 vitórias."""

# A fazer

"""4. Recuperar os jogadores nascidos na década de 90."""

# A fazer

"""5. Recuperar o nome dos jogadores que atuam pela equipe 'Real F. C.'"""

# A fazer

"""6. Recuperar o nome e o CPF de todos os jogadores que atuam na posição 'Goleiro'."""

# A fazer

"""7. Recuperar os dados do jogador que mais fez gols no campeonato (artilheiro)."""

# A fazer

"""8. Recuperar os times ordenados decrescentemente pelo número de vitórias, e pelo número de empates caso o número de vitórias seja igual."""

# A fazer

"""9. Recuperar o número de gols marcados e o número de gols sofridos pela equipe 'Sport F. C.'."""

# A fazer

"""10. Recuperar a equipe que tem o maior número de derrotas."""

# A fazer

"""11. Recuperar a média dos salários dos jogadores da equipe 'River F. C.'"""

# A fazer

"""12. Recuperar o nome dos jogadores que atuaram pela equipe 'America F. C.' na rodada número 3."""

# A fazer

"""13. Recuperar o nome das equipes que venceram na rodada 7."""

# A fazer

"""14. Recuperar as equipes ordenadas decrescentemente pela média do público dos jogos em que foi mandante."""

# A fazer

"""15. Recuperar o número de cartões obtidos pela equipe 'Lake Trinity' durante o campeonato."""

# A fazer

"""16. Recuperar o número de cartões obtidos pela equipe 'Real F. C.' durante o campeonato."""

# A fazer

"""17. Recuperar as equipes ordenadas decrescentemente pela média salarial de seus jogadores."""

# A fazer

"""18. Atualizar o número de vitórias da equipe 'Porto F. C.' para 1."""

# A fazer

"""19. Atualizar o número de gols marcados pelo jogador de CPF '1493017907' na partida código '181' para 2."""

# A fazer

"""# Manipulação de Arquivos .csv

1. Leitura de dados .csv
"""

#Lê dados de um arquivo .csv local
df = pd.read_csv("Jogadores_America.csv")

#Lê dados de um arquivo .csv da Web
df = pd.read_csv("http://professor.ufop.br/sites/default/files/george/files/jogadores_america.csv")
print("Jogadores:")
print(df)

"""2. Adição de coluna a um DataFrame"""

#Adiciona a coluna Status ao DataFrame df
status = ["Disponivel",
          "Lesionado",
          "Disponivel",
          "Disponivel",
          "Suspenso",
          "Disponivel",
          "Disponivel",
          "Disponivel",
          "Disponivel",
          "Lesionado",
          "Disponivel",
          "Disponivel",
          "Suspenso",
          "Disponivel",
          "Disponivel",
          "Disponivel"]
df["Status"] = status
print("\nJogadores com Status:")
print(df)

"""3. Imprime apenas a coluna "Salario" do DataFrame"""

print(df["Salario"])

"""4. Escreve os dados alterados em Jogadores_America_Update.csv"""

df.to_csv(r'Jogadores_America_Update.csv', index = False)

"""X. Exiba, para cada equipe, o nome de seu jogador mais velho."""

# A fazer (extra!)